macro(dox_add_croutine _name)
    enable_language(ASM)
    SET(ASM_OPTIONS "-x assembler-with-cpp")
    SET(CMAKE_ASM_FLAGS "${CFLAGS} ${ASM_OPTIONS}")
    
    set(asm_file "${ARGN}/detail/swap_x86_64.S")
    if (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
        set(ARCH "x86_64")
    elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "amd64")
        set(ARCH "x86_64")
    elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "AMD64")
        if (CMAKE_CL_64)
    	    set(ARCH "x86_64")
        else()
    	    set(ARCH "x86")
        endif()
    elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86")
        set(ARCH "x86")
    elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i386")
        set(ARCH "x86")
    elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i686")
        set(ARCH "x86")
    elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "arm")
        set(ARCH "arm")
        set(asm_file "${ARGN}/detail/swap_aarch.S")
    else()
        message(FATAL_ERROR "Unknown processor:" ${CMAKE_SYSTEM_PROCESSOR})
    endif()
    
    file(GLOB_RECURSE SRCS "${ARGN}/*.cc")
    list(APPEND SRCS ${asm_file})
    add_library(${_name} SHARED ${SRCS})

endmacro(dox_add_croutine _name)
